//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanHang.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auth
    {
        public int authId { get; set; }
        public Nullable<int> userId { get; set; }
        public string password_ { get; set; }
        public string username { get; set; }
    
        public virtual User User { get; set; }
    }
}
