//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanHang.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class filter
    {
        public Nullable<int> tagId { get; set; }
        public Nullable<int> productId { get; set; }
        public int fiterId { get; set; }
    
        public virtual product product { get; set; }
        public virtual tag tag { get; set; }
    }
}
